# Generated by Django 4.2.23 on 2025-06-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin'), ('banned', 'Banned')], default='regular', max_length=10)),
                ('activity', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
