# Generated by Django 4.2.23 on 2025-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_user_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_eid', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=84)),
                ('image_url', models.TextField(max_length=2000)),
                ('blog_content', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=10)),
            ],
        ),
    ]
