# Generated by Django 5.2.3 on 2025-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='eid',
            field=models.CharField(default='', max_length=128),
        ),
    ]
