# Generated by Django 5.2.3 on 2025-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(default='technology', max_length=20),
        ),
        migrations.AddField(
            model_name='blogs',
            name='excerpt',
            field=models.CharField(default='', max_length=500),
        ),
    ]
